export const locations = [
  {
    id: 1,
    name: 'The Hoop House',
    address: '100 Congress Ave',
    city: 'Austin, TX 78701',
    distance: '1.2 miles away',
    status: 'active',
    cityValue: 'austin',
  },
  {
    id: 2,
    name: 'Austin Sports Center',
    address: '425 Woodward St',
    city: 'Austin, TX 78704',
    distance: '3.4 miles away',
    status: 'active',
    cityValue: 'austin',
  },
  {
    id: 3,
    name: 'Round Rock SC',
    address: '2400 Chisholm Trail',
    city: 'Round Rock, TX 78681',
    distance: '15.2 miles away',
    status: 'active',
    cityValue: 'austin',
  },
  {
    id: 4,
    name: 'Cedar Park Hoops',
    address: '1800 E Whitestone Blvd',
    city: 'Cedar Park, TX 78613',
    distance: '18.5 miles away',
    status: 'coming-soon',
    cityValue: 'austin',
  },
  {
    id: 5,
    name: 'Dallas Indoor Club',
    address: '1200 Main St',
    city: 'Dallas, TX 75202',
    distance: '195 miles away',
    status: 'active',
    cityValue: 'dallas',
  },
  {
    id: 6,
    name: 'Metro Volley Complex',
    address: '500 S Ervay St',
    city: 'Dallas, TX 75201',
    distance: '196 miles away',
    status: 'active',
    cityValue: 'dallas',
  },
  {
    id: 7,
    name: 'Plano Court Time',
    address: '2000 E Spring Creek',
    city: 'Plano, TX 75074',
    distance: '210 miles away',
    status: 'coming-soon',
    cityValue: 'dallas',
  },
  {
    id: 8,
    name: 'Windy City Courts',
    address: '150 W Roosevelt Rd',
    city: 'Chicago, IL 60605',
    distance: '950 miles away',
    status: 'active',
    cityValue: 'chicago',
  },
];

export const cityOptions = [
  { value: 'austin', label: 'Austin, TX' },
  { value: 'dallas', label: 'Dallas, TX' },
  { value: 'chicago', label: 'Chicago, IL' },
  { value: 'miami', label: 'Miami, FL' },
  { value: 'atlanta', label: 'Atlanta, GA' },
];

export const mapPositions = {
  1: { top: '30%', left: '25%' },
  2: { top: '40%', left: '55%' },
  3: { top: '25%', left: '75%' },
  4: { top: '55%', left: '45%' },
  5: { top: '70%', left: '20%' },
  6: { top: '65%', left: '60%' },
  7: { top: '80%', left: '80%' },
  8: { top: '45%', left: '35%' },
};
